import type { NewsSiteRules } from './news-site-rules.ts';

// Official government press-release templates reviewed against public HTML.
export const GOVERNMENT_NEWS_SITES: Array<NewsSiteRules & { host: string; path: RegExp }> = [
  {
    host: 'mohw.gov.tw',
    path: /^\/cp-16-\d+-1\.html$/i,
    bodySelector: 'article.cpArticle',
    plainTextBody: true,
    titleSelector: '.pageHeader h2',
    publishedSelector: 'meta[name="DC.Date"]',
    publishedAttribute: 'content',
  },
  {
    host: 'mol.gov.tw',
    path: /^\/1607\/1632\/1633\/\d+(?:\/post)?\/?$/,
    bodySelector: 'section.cp',
    bodyExcludeSelector: '.publish_info_top, .publish_info_down, .pic, .related_photoblock',
    titleSelector: 'h2.title',
    publishedSelector: '.publish_info_down li:contains("發布日期")',
    publicationPattern: /發布日期[:：]\s*(\d{4}-\d{2}-\d{2})/,
    preferPrintedPublication: true,
  },
  {
    host: 'moi.gov.tw',
    path: /^\/News_Content\.aspx\?/i,
    bodySelector: '.page-content .essay > .p',
    trustContainer: true,
    plainTextBody: true,
    titleSelector: '.page-content h3',
    publishedSelector: '.page-content li:contains("發布日期")',
    publicationPattern: /發布日期[：:]\s*(\d{3}-\d{2}-\d{2}\s+\d{2}:\d{2})/,
    publicationFormat: 'roc',
    preferPrintedPublication: true,
  },
  {
    host: 'mofa.gov.tw',
    path: /^\/News_Content\.aspx\?/i,
    bodySelector: '.page-content .essay > .p',
    trustContainer: true,
    plainTextBody: true,
    titleSelector: '.page-content h3',
    publishedSelector: '.page-content li:contains("發布時間")',
    publicationPattern: /發布時間[：:]\s*(\d{4}-\d{2}-\d{2})/,
    preferPrintedPublication: true,
  },
  {
    host: 'moa.gov.tw',
    path: /^\/theme_data\.php\?/i,
    bodySelector: '#content > .edit',
    titleSelector: '#content > h2.fs-3',
    publishedSelector: 'meta[name="Create_Date"]',
    publishedAttribute: 'content',
  },
  {
    host: 'mnd.gov.tw',
    path: /^\/news\/(?:pressrelease|mnd)\/\d+\/?$/i,
    bodySelector: '.maincontent',
    plainTextBody: true,
    preferShortBody: true,
    titleSelector: 'h2.headline-h2',
    publishedSelector: '.pageinfo > .body-2',
    publicationPattern: /(\d{3}\.\d{2}\.\d{2})/,
    publicationFormat: 'roc',
    preferPrintedPublication: true,
  },
  {
    host: 'gov.taipei',
    path: /^\/News_Content\.aspx\?n=F0DDAF49B89E9413&sms=72544237BBE4C5F6&s=[A-F0-9]+$/i,
    bodySelector: '.area-essay.page-caption-p .essay',
    trustContainer: true,
    plainTextBody: true,
    publishedSelector: '.bottom-detail li:contains("發布日期")',
    publicationPattern: /發布日期[：:]\s*(\d{2,3}-\d{2}-\d{2})/,
    publicationFormat: 'roc',
    preferPrintedPublication: true,
  },
  {
    host: 'ntpc.gov.tw',
    path: /^\/ch\/home\.jsp\?id=e8ca970cde5c00e1&dataserno=[a-f0-9]+$/i,
    bodySelector: '#printcontent .detail > .edit',
    plainTextBody: true,
    titleSelector: '#printcontent .d_title',
    publishedSelector: '#printcontent .top_note li:contains("發佈日期") .text-body',
    preferPrintedPublication: true,
  },
  {
    host: 'president.gov.tw',
    path: /^\/NEWS\/\d+\/?$/i,
    bodySelector: '.pageWrap1 > .article1',
    titleSelector: '.pageWrap1 > .pageTitle1',
    publishedSelector: '.pageWrap1 > .pageDate1 > .date',
    publicationFormat: 'roc',
    publicationPattern: /^(\d{3}年\d{1,2}月\d{1,2}日)$/,
    // This site's JSON-LD reuses the section's 2017 creation date and headline.
    preferPrintedPublication: true,
    // Some final paragraphs are direct text nodes outside <p> elements.
    plainTextBody: true,
    preferShortBody: true,
  },
];
