"""Generate the liveboard's offline wordmark with the same font as brand-assets.py.

Usage: python tools/offline-wordmark.py /path/to/NotoSerifTC-SemiBold.otf
Requires fontTools; Noto Serif TC is licensed under SIL OFL.
"""
import pathlib
import sys

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

font = TTFont(sys.argv[1])
glyphs = font.getGlyphSet()
cmap = font.getBestCmap()
paths = []
for index, char in enumerate('離線中嗚嗚嗚'):
    pen = SVGPathPen(glyphs)
    glyphs[cmap[ord(char)]].draw(pen)
    paths.append(
        f'      <path transform="translate({index * 100} 0) scale(0.1 -0.1) translate(0 -880)" d="{pen.getCommands()}" />'
    )

output = pathlib.Path(__file__).resolve().parents[1] / 'web/src/app/liveboard/OfflineWordmark.tsx'
output.write_text(
    '// Generated by tools/offline-wordmark.py from Noto Serif TC SemiBold (SIL OFL), matching Wordmark.\n'
    'export default function OfflineWordmark() {\n'
    '  return (\n'
    '    <svg viewBox="0 0 600 100" className="h-full w-full" fill="currentColor" aria-hidden="true">\n'
    + '\n'.join(paths)
    + '\n    </svg>\n  );\n}\n'
)
